/* ============================================
   MOCK DATA — Simulates Laravel API responses
   ============================================ */

export const heroData = {
  headline: 'Crafted for Eternity',
  subheadline: 'Timeless jewelry, handcrafted with passion and precision',
  cta: 'Explore Collection',
  image: 'https://images.unsplash.com/photo-1515562141589-67f0d569b610?q=80&w=1920',
};

export const collections = [
  {
    id: 1,
    name: 'Celestial Rings',
    slug: 'celestial-rings',
    description: 'Symbols of everlasting devotion.',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800',
    count: 6,
  },
  {
    id: 2,
    name: 'Majestic Necklaces',
    slug: 'majestic-necklaces',
    description: 'Elegance that transcends generations.',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800',
    count: 6,
  },
  {
    id: 3,
    name: 'Radiant Earrings',
    slug: 'radiant-earrings',
    description: 'Grace in every movement.',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800',
    count: 6,
  },
  {
    id: 4,
    name: 'Infinite Bracelets',
    slug: 'infinite-bracelets',
    description: 'Brilliance on your wrist.',
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=800',
    count: 6,
  },
  {
    id: 5,
    name: 'Timeless Pendants',
    slug: 'timeless-pendants',
    description: 'Heritage and history in every piece.',
    image: 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=800',
    count: 6,
  },
];

export const products = [
  // Celestial Rings (1-6)
  {
    id: 1,
    name: 'Celestial Solitaire Ring',
    slug: 'celestial-solitaire-ring',
    price: 4250,
    category: 'Rings',
    collection: 'Celestial Rings',
    images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800'],
    description: '18K white gold with 1.2ct diamond.',
    specs: { material: '18K White Gold', stone: 'Diamond (1.2ct)', clarity: 'VVS1', weight: '4.2g' },
    rating: 4.9,
    reviews: 47,
    inStock: true,
    badge: 'Best Seller',
  },
  {
    id: 2,
    name: 'Lunar Eclipse Band',
    slug: 'lunar-eclipse-band',
    price: 1850,
    category: 'Rings',
    collection: 'Celestial Rings',
    images: ['https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800'],
    description: 'Mystical black diamond eternity band.',
    specs: { material: '14K Black Gold', stone: 'Black Diamond', weight: '3.5g' },
    rating: 4.7,
    reviews: 12,
    inStock: true,
  },
  {
    id: 3,
    name: 'Starlight Pavé Ring',
    slug: 'starlight-pave-ring',
    price: 2400,
    category: 'Rings',
    collection: 'Celestial Rings',
    images: ['https://images.unsplash.com/photo-1544451240-8451121d5964?q=80&w=800'],
    description: 'Micro-pavé diamonds on a thin gold band.',
    specs: { material: '18K Yellow Gold', stone: 'Diamond Pavé', weight: '2.8g' },
    rating: 4.8,
    reviews: 25,
    inStock: true,
  },
  {
    id: 4,
    name: 'Nova Diamond Ring',
    slug: 'nova-diamond-ring',
    price: 5200,
    category: 'Rings',
    collection: 'Celestial Rings',
    images: ['https://images.unsplash.com/photo-1598560912015-6213717278d2?q=80&w=800'],
    description: 'Explosion of brilliance with center emerald cut.',
    specs: { material: 'Platinum', stone: 'Emerald Cut Diamond', weight: '5.1g' },
    rating: 5.0,
    reviews: 8,
    inStock: true,
    badge: 'New',
  },
  {
    id: 5,
    name: 'Galaxy Twist Ring',
    slug: 'galaxy-twist-ring',
    price: 2100,
    category: 'Rings',
    collection: 'Celestial Rings',
    images: ['https://images.unsplash.com/photo-1617038220319-276d3cfab638?q=80&w=800'],
    description: 'Intertwined bands of rose and white gold.',
    specs: { material: '18K Two-Tone Gold', weight: '4.5g' },
    rating: 4.6,
    reviews: 19,
    inStock: true,
  },
  {
    id: 6,
    name: 'Nebula Opal Ring',
    slug: 'nebula-opal-ring',
    price: 1650,
    category: 'Rings',
    collection: 'Celestial Rings',
    images: ['https://images.unsplash.com/photo-1588444837495-c6cfaf504670?q=80&w=800'],
    description: 'Iridescent opal surrounded by cosmic diamonds.',
    specs: { material: '14K Yellow Gold', stone: 'Natural Opal', weight: '3.2g' },
    rating: 4.9,
    reviews: 31,
    inStock: true,
  },

  // Majestic Necklaces (7-12)
  {
    id: 7,
    name: 'Royal Majesty Choker',
    slug: 'royal-majesty-choker',
    price: 7500,
    category: 'Necklaces',
    collection: 'Majestic Necklaces',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800'],
    description: 'Fit for royalty, featuring rubies and pearls.',
    specs: { material: '22K Gold', stone: 'Ruby & Pearl', weight: '45g' },
    rating: 5.0,
    reviews: 5,
    inStock: true,
    badge: 'Exclusive',
  },
  {
    id: 8,
    name: 'Imperial Pearl Necklace',
    slug: 'imperial-pearl-necklace',
    price: 3800,
    category: 'Necklaces',
    collection: 'Majestic Necklaces',
    images: ['https://images.unsplash.com/photo-1515562141589-67f0d569b610?q=80&w=800'],
    description: 'Hand-selected South Sea pearls.',
    specs: { material: '18K White Gold', stone: 'South Sea Pearl', length: '18"' },
    rating: 4.8,
    reviews: 22,
    inStock: true,
  },
  {
    id: 9,
    name: 'Empress Emerald Pendant',
    slug: 'empress-emerald-pendant',
    price: 4900,
    category: 'Necklaces',
    collection: 'Majestic Necklaces',
    images: ['https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=800'],
    description: 'Vibrant Colombian emerald in 22K gold.',
    specs: { material: '22K Gold', stone: 'Colombian Emerald', weight: '8.5g' },
    rating: 4.9,
    reviews: 14,
    inStock: true,
  },
  {
    id: 10,
    name: 'Sovereign Gold Chain',
    slug: 'sovereign-gold-chain',
    price: 3200,
    category: 'Necklaces',
    collection: 'Majestic Necklaces',
    images: ['https://images.unsplash.com/photo-1611085583191-a3b1a308c021?q=80&w=800'],
    description: 'Heavy 24K solid gold braided chain.',
    specs: { material: '24K Gold', weight: '30g', style: 'Braided' },
    rating: 4.7,
    reviews: 40,
    inStock: true,
  },
  {
    id: 11,
    name: 'Regency Diamond Collier',
    slug: 'regency-diamond-collier',
    price: 9800,
    category: 'Necklaces',
    collection: 'Majestic Necklaces',
    images: ['https://images.unsplash.com/photo-1624479355528-25000ca04f04?q=80&w=800'],
    description: 'Sophisticated cascade of brilliant diamonds.',
    specs: { material: 'Platinum', stone: 'Brilliant Diamond', weight: '55g' },
    rating: 5.0,
    reviews: 3,
    inStock: true,
  },
  {
    id: 12,
    name: 'Monarch Sapphire Necklace',
    slug: 'monarch-sapphire-necklace',
    price: 5500,
    category: 'Necklaces',
    collection: 'Majestic Necklaces',
    images: ['https://images.unsplash.com/photo-1599643477877-537ef527848f?q=80&w=800'],
    description: 'Deep blue sapphire surrounded by diamonds.',
    specs: { material: '18K White Gold', stone: 'Sapphire', weight: '12g' },
    rating: 4.9,
    reviews: 17,
    inStock: true,
  },

  // Radiant Earrings (13-18)
  {
    id: 13,
    name: 'Solar Flare Studs',
    slug: 'solar-flare-studs',
    price: 2800,
    category: 'Earrings',
    collection: 'Radiant Earrings',
    images: ['https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800'],
    description: 'Brilliant yellow diamond studs.',
    specs: { material: '18K Gold', stone: 'Yellow Diamond', weight: '2.5g' },
    rating: 4.8,
    reviews: 9,
    inStock: true,
  },
  {
    id: 14,
    name: 'Aurora Drop Earrings',
    slug: 'aurora-drop-earrings',
    price: 3100,
    category: 'Earrings',
    collection: 'Radiant Earrings',
    images: ['https://images.unsplash.com/photo-1598560912015-6213717278d2?q=80&w=800'],
    description: 'Pavé set diamonds inspired by Northern Lights.',
    specs: { material: '18K White Gold', stone: 'Diamond Pavé', style: 'Drop' },
    rating: 5.0,
    reviews: 21,
    inStock: true,
  },
  {
    id: 15,
    name: 'Prism Halo Earrings',
    slug: 'prism-halo-earrings',
    price: 2200,
    category: 'Earrings',
    collection: 'Radiant Earrings',
    images: ['https://images.unsplash.com/photo-1617038220319-276d3cfab638?q=80&w=800'],
    description: 'Geometric design with a central diamond halo.',
    specs: { material: '18K Rose Gold', stone: 'Diamond Halo', weight: '3.8g' },
    rating: 4.7,
    reviews: 15,
    inStock: true,
  },
  {
    id: 16,
    name: 'Crystal Cascade Drops',
    slug: 'crystal-cascade-drops',
    price: 1450,
    category: 'Earrings',
    collection: 'Radiant Earrings',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800'],
    description: 'Long flowing drops of clear crystals.',
    specs: { material: 'Sterling Silver', stone: 'Clear Crystal', length: '2.5"' },
    rating: 4.6,
    reviews: 28,
    inStock: true,
  },
  {
    id: 17,
    name: 'Luminous Hoop Earrings',
    slug: 'luminous-hoop-earrings',
    price: 1950,
    category: 'Earrings',
    collection: 'Radiant Earrings',
    images: ['https://images.unsplash.com/photo-1589128777073-263566ae5e4d?q=80&w=800'],
    description: 'Classic 18K gold hoops with internal diamonds.',
    specs: { material: '18K Gold', stone: 'Diamond', style: 'Hoop' },
    rating: 4.8,
    reviews: 35,
    inStock: true,
  },
  {
    id: 18,
    name: 'Vivid Ruby Studs',
    slug: 'vivid-ruby-studs',
    price: 2600,
    category: 'Earrings',
    collection: 'Radiant Earrings',
    images: ['https://images.unsplash.com/photo-1626784215021-2e39ccf971cd?q=80&w=800'],
    description: 'Intense red rubies in a crown setting.',
    specs: { material: '18K Gold', stone: 'Ruby', weight: '2.2g' },
    rating: 4.9,
    reviews: 11,
    inStock: true,
  },

  // Infinite Bracelets (19-24)
  {
    id: 19,
    name: 'Eternal Link Bracelet',
    slug: 'eternal-link-bracelet',
    price: 3400,
    category: 'Bracelets',
    collection: 'Infinite Bracelets',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=800'],
    description: 'Solid gold links that never go out of style.',
    specs: { material: '18K Gold', weight: '25g', style: 'Link' },
    rating: 4.9,
    reviews: 18,
    inStock: true,
  },
  {
    id: 20,
    name: 'Infinity Knot Bangle',
    slug: 'infinity-knot-bangle',
    price: 2150,
    category: 'Bracelets',
    collection: 'Infinite Bracelets',
    images: ['https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=800'],
    description: 'Elegant gold bangle with a central infinity knot.',
    specs: { material: '14K Gold', weight: '12g', style: 'Bangle' },
    rating: 4.7,
    reviews: 14,
    inStock: true,
  },
  {
    id: 21,
    name: 'Serenity Cuff',
    slug: 'serenity-cuff',
    price: 1800,
    category: 'Bracelets',
    collection: 'Infinite Bracelets',
    images: ['https://images.unsplash.com/photo-1515562141589-67f0d569b610?q=80&w=800'],
    description: 'Minimalist brushed gold cuff for daily wear.',
    specs: { material: '18K Gold', weight: '15g', finish: 'Brushed' },
    rating: 4.5,
    reviews: 22,
    inStock: true,
  },
  {
    id: 22,
    name: 'Harmonious Tennis Bracelet',
    slug: 'harmonious-tennis-bracelet',
    price: 6500,
    category: 'Bracelets',
    collection: 'Infinite Bracelets',
    images: ['https://images.unsplash.com/photo-1611591437248-2651475c7423?q=80&w=800'],
    description: 'Continuous line of diamonds in 18K white gold.',
    specs: { material: '18K White Gold', stone: 'Diamond', totalWeight: '5ct' },
    rating: 5.0,
    reviews: 7,
    inStock: true,
    badge: 'Best Seller',
  },
  {
    id: 23,
    name: 'Endless Charm Bracelet',
    slug: 'endless-charm-bracelet',
    price: 2800,
    category: 'Bracelets',
    collection: 'Infinite Bracelets',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=800'],
    description: 'Add your own story with unique gold charms.',
    specs: { material: '18K Gold', includes: '3 Starter Charms' },
    rating: 4.8,
    reviews: 16,
    inStock: true,
  },
  {
    id: 24,
    name: 'Boundless Gold Bangle',
    slug: 'boundless-gold-bangle',
    price: 2400,
    category: 'Bracelets',
    collection: 'Infinite Bracelets',
    images: ['https://images.unsplash.com/photo-1515562141207-7a8efd3f84f3?q=80&w=800'],
    description: 'Hammered gold finish for a textured look.',
    specs: { material: '18K Gold', finish: 'Hammered', weight: '18g' },
    rating: 4.6,
    reviews: 13,
    inStock: true,
  },

  // Timeless Pendants (25-30)
  {
    id: 25,
    name: 'Legacy Heart Pendant',
    slug: 'legacy-heart-pendant',
    price: 1200,
    category: 'Pendants',
    collection: 'Timeless Pendants',
    images: ['https://images.unsplash.com/photo-1515562141207-7a8efd3f84f3?q=80&w=800'],
    description: 'Engravable gold heart with a tiny diamond.',
    specs: { material: '14K Gold', stone: 'Diamond', weight: '2.5g' },
    rating: 4.8,
    reviews: 30,
    inStock: true,
  },
  {
    id: 26,
    name: 'Ancestral Locket',
    slug: 'ancestral-locket',
    price: 1850,
    category: 'Pendants',
    collection: 'Timeless Pendants',
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=800'],
    description: 'Vintage style locket in antique gold finish.',
    specs: { material: '18K Gold', finish: 'Antique', feature: 'Photo Locket' },
    rating: 4.9,
    reviews: 12,
    inStock: true,
  },
  {
    id: 27,
    name: 'Everlasting Cross Pendant',
    slug: 'everlasting-cross-pendant',
    price: 2200,
    category: 'Pendants',
    collection: 'Timeless Pendants',
    images: ['https://images.unsplash.com/photo-1611085583191-a3b1a308c021?q=80&w=800'],
    description: 'Diamond encrusted cross on a delicate chain.',
    specs: { material: '18K White Gold', stone: 'Diamond', weight: '5.2g' },
    rating: 4.7,
    reviews: 25,
    inStock: true,
  },
  {
    id: 28,
    name: 'Historic Medallion',
    slug: 'historic-medallion',
    price: 2900,
    category: 'Pendants',
    collection: 'Timeless Pendants',
    images: ['https://images.unsplash.com/photo-1599643477877-537ef527848f?q=80&w=800'],
    description: 'Embossed gold medallion with historical motifs.',
    specs: { material: '22K Gold', weight: '12g', style: 'Medallion' },
    rating: 4.8,
    reviews: 19,
    inStock: true,
  },
  {
    id: 29,
    name: 'Classic Teardrop Pendant',
    slug: 'classic-teardrop-pendant',
    price: 3400,
    category: 'Pendants',
    collection: 'Timeless Pendants',
    images: ['https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=800'],
    description: 'A single pear-shaped sapphire on white gold.',
    specs: { material: '18K White Gold', stone: 'Sapphire', weight: '4.8g' },
    rating: 5.0,
    reviews: 6,
    inStock: true,
  },
  {
    id: 30,
    name: 'Vintage Key Charm',
    slug: 'vintage-key-charm',
    price: 950,
    category: 'Pendants',
    collection: 'Timeless Pendants',
    images: ['https://images.unsplash.com/photo-1515562141207-7a8efd3f84f3?q=80&w=800'],
    description: 'Ornate key design in 18K yellow gold.',
    specs: { material: '18K Gold', style: 'Vintage Key', weight: '3.1g' },
    rating: 4.6,
    reviews: 14,
    inStock: true,
  },
];

export const storyContent = {
  title: 'The Art of Forever',
  subtitle: 'Our Heritage',
  body: 'Every piece in the Tori Crown collection is born from a century-old tradition of master craftsmanship. Our artisans pour their soul into every setting, every polish, every stone — creating jewelry that doesn\'t just adorn, but tells a story.',
  signature: '— House of Tori Crown, est. 1926',
  image: 'https://images.unsplash.com/photo-1512163143273-bde0e3cc7407?q=80&w=1200',
};

export const trustBadges = [
  { icon: 'shield', title: 'Authenticity Guaranteed', description: 'Every piece comes with a certificate of authenticity' },
  { icon: 'gem', title: 'Certified Diamonds', description: 'GIA certified stones with full grading reports' },
  { icon: 'truck', title: 'Insured Shipping', description: 'Complimentary insured delivery worldwide' },
  { icon: 'refresh', title: '30-Day Returns', description: 'Hassle-free returns within 30 days' },
];

export const reviews = [
  { id: 1, author: 'Sophia M.', rating: 5, date: '2024-12-15', text: 'Absolutely breathtaking. The craftsmanship is unlike anything I\'ve ever seen. Worth every penny.', product: 'Celestial Solitaire Ring', verified: true },
  { id: 2, author: 'James R.', rating: 5, date: '2024-11-28', text: 'Purchased for my wife\'s anniversary. She was speechless. The quality speaks for itself.', product: 'Royal Majesty Choker', verified: true },
  { id: 3, author: 'Elena K.', rating: 4, date: '2024-11-10', text: 'Beautiful earrings with incredible sparkle. The packaging was also very luxurious.', product: 'Aurora Drop Earrings', verified: true },
  { id: 4, author: 'Michael T.', rating: 5, date: '2024-10-22', text: 'Exceptional quality and the customer service was outstanding. They helped me choose the perfect size.', product: 'Eternal Link Bracelet', verified: true },
];

export const banners = [
  { id: 1, title: 'New Arrivals', subtitle: 'The Spring Collection is here', image: 'https://images.unsplash.com/photo-1611085583191-a3b1a308c021?q=80&w=1920', link: '/collections' },
  { id: 2, title: 'Bridal Edit', subtitle: 'Begin your forever', image: 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=1920', link: '/collections' },
];
